include "constants.asm"

include "code/int.asm"
include "code/rst.asm"
include "code/header.asm"
include "code/init.asm"
include "code/alias.asm"
include "code/joypad.asm"
include "code/video/copy.asm"
include "code/task.asm"
